//! `gritt-agent skill sync`: regenerates `.claude/skills/*/SKILL.md` stubs
//! and the `agents/openai.yaml` policy block beside each canonical skill.

use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use crate::frontmatter::{extract_block, split_fence, split_lines, Split};
use crate::fsx::{self, relative_posix};
use crate::repo::skills_root;
use crate::{CliError, Result};

pub const GENERATED_MARKER: &str = "<!-- GENERATED BY gritt-agent skill sync; DO NOT EDIT -->";
const LEGACY_MARKERS: [&str; 5] = [
    "<!-- GENERATED BY nx run agent-tools:sync-skills; DO NOT EDIT -->",
    "<!-- GENERATED BY sync-skills.mjs; DO NOT EDIT -->",
    "<!-- GENERATED BY sync_skills.py; DO NOT EDIT -->",
    "<!-- GENERATED BY sync_claude_skills.py; DO NOT EDIT -->",
    "# Claude Compatibility Stub",
];
const INTERFACE_KEYS: [&str; 3] = ["display_name", "short_description", "default_prompt"];

#[derive(Debug, Clone, Copy, Default)]
pub struct SyncOptions {
    pub check: bool,
    pub prune: bool,
}

/// What a sync did or, in check mode, would do. Printing is separate so a
/// command that scaffolds a skill can announce its own files first.
#[derive(Debug, Default)]
pub struct Summary {
    pub check: bool,
    /// Generated files written, or out of sync in check mode.
    pub drift: Vec<String>,
}

impl Summary {
    pub fn exit_code(&self) -> i32 {
        i32::from(self.check && !self.drift.is_empty())
    }

    /// Prints the summary exactly as `skill sync` reports it.
    pub fn print(&self) {
        if self.check {
            if self.drift.is_empty() {
                println!("sync_skills ok (no drift)");
                return;
            }
            for item in &self.drift {
                eprintln!("drift: {item}");
            }
            eprintln!(
                "sync_skills: {} file(s) out of sync with SKILL.md",
                self.drift.len()
            );
            return;
        }
        println!(
            "synced skill adapters ({} file(s) updated)",
            self.drift.len()
        );
    }
}

/// Runs the sync, prints its summary, and returns the exit code.
pub fn run(repo: &Path, options: SyncOptions) -> Result<i32> {
    let summary = sync(repo, options)?;
    summary.print();
    Ok(summary.exit_code())
}

/// Runs the sync without printing the summary. Warnings about user-owned
/// files still go to stderr as they are found.
pub fn sync(repo: &Path, options: SyncOptions) -> Result<Summary> {
    let source_root = skills_root(repo);
    if !fsx::is_dir(&source_root) {
        return Err(CliError::new(format!(
            "missing canonical skills root: {}",
            source_root.display()
        )));
    }
    let mut skill_dirs = Vec::new();
    for entry in fsx::list_dirs(&source_root)? {
        if fsx::exists(&entry.path.join("SKILL.md")) {
            skill_dirs.push(entry.path);
        }
    }

    let mut drift = sync_claude_stubs(repo, &skill_dirs, options)?;
    drift.extend(sync_codex_metadata(repo, &skill_dirs, options.check)?);
    Ok(Summary {
        check: options.check,
        drift,
    })
}

fn sync_claude_stubs(
    repo: &Path,
    skill_dirs: &[PathBuf],
    options: SyncOptions,
) -> Result<Vec<String>> {
    let target_root = repo.join(".claude").join("skills");
    let mut changed = Vec::new();
    if let Ok(info) = fs::symlink_metadata(&target_root) {
        if info.file_type().is_symlink() {
            if options.check {
                return Ok(vec![format!(
                    "{} (symlink)",
                    relative_posix(repo, &target_root)
                )]);
            }
            fs::remove_file(&target_root)?;
        }
    }
    if !options.check {
        fs::create_dir_all(&target_root)?;
    } else if !fsx::is_dir(&target_root) {
        return Ok(skill_dirs
            .iter()
            .map(|dir| relative_posix(repo, &target_root.join(dir_name(dir)).join("SKILL.md")))
            .collect());
    }

    let mut expected = BTreeSet::new();
    for skill_dir in skill_dirs {
        let name = dir_name(skill_dir);
        expected.insert(name.clone());
        let target = target_root.join(&name).join("SKILL.md");
        let desired = render_stub(repo, &skill_dir.join("SKILL.md"))?;
        if fsx::exists(&target) && !is_generated_stub(&target) {
            if !options.check {
                eprintln!(
                    "warning: preserving user-owned Claude skill stub: {}",
                    target.display()
                );
            }
            continue;
        }
        let current = fsx::read_text_or(&target, "")?;
        if current == desired {
            continue;
        }
        changed.push(relative_posix(repo, &target));
        if !options.check {
            fsx::write_text(&target, &desired)?;
        }
    }

    if fsx::is_dir(&target_root) {
        for entry in fsx::list_dirs(&target_root)? {
            if expected.contains(&entry.name) {
                continue;
            }
            if is_generated_skill_dir(&entry.path)? {
                changed.push(format!("{} (stale)", relative_posix(repo, &entry.path)));
                if !options.check {
                    fsx::remove_dir_all(&entry.path)?;
                }
            } else if options.prune && !options.check {
                eprintln!(
                    "warning: --prune requested but preserving user-owned Claude skill dir: {}",
                    entry.path.display()
                );
            }
        }
    }
    Ok(changed)
}

fn sync_codex_metadata(repo: &Path, skill_dirs: &[PathBuf], check: bool) -> Result<Vec<String>> {
    let mut changed = Vec::new();
    for skill_dir in skill_dirs {
        let skill_file = skill_dir.join("SKILL.md");
        let metadata = parse_skill_frontmatter(&fsx::read_text(&skill_file)?);
        let name = metadata
            .get("name")
            .cloned()
            .unwrap_or_else(|| dir_name(skill_dir));
        let allow_implicit = !as_bool(metadata.get("disable-model-invocation").map(String::as_str));
        let target = skill_dir.join("agents").join("openai.yaml");
        let interface = match read_interface(&target)? {
            Some(existing) => existing,
            None => default_interface(
                &name,
                metadata
                    .get("description")
                    .map(String::as_str)
                    .unwrap_or(""),
            ),
        };
        let desired = render_openai_yaml(&interface, allow_implicit);
        let current = fsx::read_text_or(&target, "")?;
        if current == desired {
            continue;
        }
        changed.push(relative_posix(repo, &target));
        if !check {
            fsx::write_text(&target, &desired)?;
        }
    }
    Ok(changed)
}

fn dir_name(dir: &Path) -> String {
    dir.file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_default()
}

pub fn render_stub(repo: &Path, skill_file: &Path) -> Result<String> {
    let content = fsx::read_text(skill_file)?;
    let frontmatter = extract_block(&content);
    let body = format!(
        "{GENERATED_MARKER}\n\n# Claude Compatibility Stub\n\nThis file exists so Claude Code can discover this project skill.\n\nCanonical skill content lives at:\n\n- `{}`\n\nRead the canonical skill file before using this skill.\n\nDo not edit this stub manually. Regenerate it from the canonical `.agents/skills/` tree.\n",
        relative_posix(repo, skill_file)
    );
    Ok(if frontmatter.is_empty() {
        body
    } else {
        format!("{frontmatter}\n\n{body}")
    })
}

/// Reads top-level `key: value` lines from a SKILL.md frontmatter block.
pub fn parse_skill_frontmatter(content: &str) -> BTreeMap<String, String> {
    let mut result = BTreeMap::new();
    let Split::Fenced(fence) = split_fence(content) else {
        return result;
    };
    for line in split_lines(fence.inner) {
        let stripped = line.trim();
        if stripped.is_empty() || stripped.starts_with('#') || !stripped.contains(':') {
            continue;
        }
        if line.starts_with(char::is_whitespace) {
            continue;
        }
        let (key, value) = stripped.split_once(':').unwrap_or((stripped, ""));
        result.insert(key.trim().to_owned(), unquote(value.trim()));
    }
    result
}

/// Reads the `interface:` block of an existing `openai.yaml`.
fn read_interface(target: &Path) -> Result<Option<Vec<(String, String)>>> {
    if !fsx::exists(target) {
        return Ok(None);
    }
    let mut result: Vec<(String, String)> = Vec::new();
    let mut in_interface = false;
    for line in split_lines(&fsx::read_text(target)?) {
        if line.starts_with("interface:") {
            in_interface = true;
            continue;
        }
        if !in_interface {
            continue;
        }
        if !line.is_empty() && !line.starts_with(char::is_whitespace) {
            break;
        }
        let stripped = line.trim();
        if stripped.is_empty() || !stripped.contains(':') {
            continue;
        }
        let (key, value) = stripped.split_once(':').unwrap_or((stripped, ""));
        let key = key.trim().to_owned();
        let value = unquote(value.trim());
        if let Some(slot) = result.iter_mut().find(|(k, _)| *k == key) {
            slot.1 = value;
        } else {
            result.push((key, value));
        }
    }
    Ok(if result.is_empty() {
        None
    } else {
        Some(result)
    })
}

/// Turns `tkt-new` into `Tkt New`.
pub fn display_name(slug: &str) -> String {
    slug.split('-')
        .map(capitalize)
        .collect::<Vec<_>>()
        .join(" ")
}

fn default_interface(name: &str, description: &str) -> Vec<(String, String)> {
    vec![
        ("display_name".to_owned(), display_name(name)),
        ("short_description".to_owned(), first_sentence(description)),
        (
            "default_prompt".to_owned(),
            format!("Use ${name} in this repository."),
        ),
    ]
}

/// The first sentence when it fits in 120 characters, else the whole text
/// when that fits, else a clipped prefix ending in `...`. A sentence ends at
/// the earliest `. `, `! `, or `? ` in the text.
pub fn first_sentence(description: &str) -> String {
    let normalized = description.split_whitespace().collect::<Vec<_>>().join(" ");
    let earliest_stop = [". ", "! ", "? "]
        .iter()
        .filter_map(|stop| normalized.find(stop))
        .min();
    if let Some(index) = earliest_stop {
        let sentence = &normalized[..index + 1];
        if sentence.chars().count() <= 120 {
            return sentence.to_owned();
        }
    }
    if normalized.chars().count() <= 120 {
        return normalized;
    }
    let mut clipped: String = normalized.chars().take(117).collect();
    if let Some(space) = clipped.rfind(' ') {
        clipped.truncate(space);
    }
    let trimmed = clipped.trim_end_matches([' ', ',', ';', ':']);
    format!("{trimmed}...")
}

fn render_openai_yaml(interface: &[(String, String)], allow_implicit: bool) -> String {
    let mut lines = vec!["interface:".to_owned()];
    for key in INTERFACE_KEYS {
        if let Some((_, value)) = interface.iter().find(|(k, _)| k == key) {
            lines.push(format!("  {key}: {}", quote_yaml(value)));
        }
    }
    lines.push("policy:".to_owned());
    lines.push(format!(
        "  allow_implicit_invocation: {}",
        if allow_implicit { "true" } else { "false" }
    ));
    format!("{}\n", lines.join("\n"))
}

fn is_generated_stub(target: &Path) -> bool {
    match fsx::read_text(target) {
        Ok(content) => {
            content.contains(GENERATED_MARKER)
                || LEGACY_MARKERS.iter().any(|marker| content.contains(marker))
        }
        Err(_) => false,
    }
}

fn is_generated_skill_dir(dir: &Path) -> Result<bool> {
    let entries = fsx::list_entries(dir)?;
    Ok(entries.len() == 1
        && entries[0].name == "SKILL.md"
        && is_generated_stub(&dir.join("SKILL.md")))
}

fn as_bool(value: Option<&str>) -> bool {
    value
        .map(|v| v.trim().eq_ignore_ascii_case("true"))
        .unwrap_or(false)
}

fn unquote(value: &str) -> String {
    let bytes = value.as_bytes();
    if bytes.len() >= 2 {
        let first = bytes[0];
        let last = bytes[bytes.len() - 1];
        if first == last && (first == b'"' || first == b'\'') {
            return value[1..value.len() - 1]
                .replace("\\\"", "\"")
                .replace("\\\\", "\\");
        }
    }
    value.to_owned()
}

pub fn quote_yaml(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

fn capitalize(value: &str) -> String {
    let mut chars = value.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn first_sentence_clips_long_text() {
        assert_eq!(
            first_sentence("Does a thing. Use when asked."),
            "Does a thing."
        );
        let long = "word ".repeat(40);
        let clipped = first_sentence(&long);
        assert!(clipped.ends_with("..."));
        assert!(clipped.len() <= 120);
    }

    #[test]
    fn first_sentence_bounds_at_120_and_stops_at_the_earliest_mark() {
        let fits = format!("{}. Second sentence.", "a".repeat(119));
        assert_eq!(first_sentence(&fits).chars().count(), 120);
        let too_long = format!("{}. Second sentence.", "a".repeat(120));
        let clipped = first_sentence(&too_long);
        assert!(clipped.ends_with("..."), "{clipped}");
        assert!(clipped.chars().count() <= 120);
        assert_eq!(first_sentence("Really? Yes. Fine! Done."), "Really?");
        assert_eq!(first_sentence("Go! Then stop. Or ask?"), "Go!");
    }

    #[test]
    fn skill_frontmatter_accepts_crlf_and_whole_line_fences() {
        let parsed = parse_skill_frontmatter(
            "---\r\nname: win\r\ndescription: CRLF.\r\n---\r\n\r\n# Win\r\n",
        );
        assert_eq!(parsed.get("name").map(String::as_str), Some("win"));
        assert_eq!(parsed.get("description").map(String::as_str), Some("CRLF."));
        let parsed =
            parse_skill_frontmatter("---\nname: x\n----\ndescription: After.\n---\n\n----\n");
        assert_eq!(
            parsed.get("description").map(String::as_str),
            Some("After.")
        );
        assert!(parse_skill_frontmatter("---\nname: x\n----\n").is_empty());
    }

    #[test]
    fn frontmatter_and_yaml_helpers() {
        let parsed = parse_skill_frontmatter(
            "---\nname: x\ndescription: \"Quoted.\"\n  nested: 1\n---\nbody",
        );
        assert_eq!(parsed.get("name").map(String::as_str), Some("x"));
        assert_eq!(
            parsed.get("description").map(String::as_str),
            Some("Quoted.")
        );
        assert!(!parsed.contains_key("nested"));
        assert_eq!(quote_yaml("a \"b\" \\"), "\"a \\\"b\\\" \\\\\"");
        assert_eq!(unquote("'x'"), "x");
    }

    #[test]
    fn default_interface_titlecases_name() {
        let interface = default_interface("tkt-new", "Creates a ticket. Use on /tkt-new.");
        assert_eq!(interface[0].1, "Tkt New");
        assert_eq!(interface[1].1, "Creates a ticket.");
        assert_eq!(interface[2].1, "Use $tkt-new in this repository.");
        assert_eq!(
            render_openai_yaml(&interface, false),
            "interface:\n  display_name: \"Tkt New\"\n  short_description: \"Creates a ticket.\"\n  default_prompt: \"Use $tkt-new in this repository.\"\npolicy:\n  allow_implicit_invocation: false\n"
        );
    }
}
