import assert from 'node:assert/strict';
import { access, mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const toolsRoot = path.dirname(fileURLToPath(import.meta.url));

function run(tool, args = [], options = {}) {
  const result = spawnSync(
    process.execPath,
    [path.join(toolsRoot, tool), ...args],
    {
      cwd: options.cwd,
      env: { ...process.env, ...options.env },
      encoding: 'utf8',
    },
  );
  assert.equal(
    result.status,
    options.status ?? 0,
    `${tool} failed\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`,
  );
  return result;
}

async function temporaryDirectory(name) {
  return mkdtemp(path.join(os.tmpdir(), `gritt--`));
}

async function write(target, content) {
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, content, 'utf8');
}

function ticketFrontmatter(id = 'TKT-0001') {
  return `---
id: ${id}
title: Test ticket
artifact: task
status: ready
owner: test
created: 2026-08-14
updated: 2026-08-14
dependencies: []
areas:
  - .agents/tools
skills: []
---

# Test ticket
`;
}

test('ticket indexes synchronize and validate in an isolated repository', async () => {
  const repo = await temporaryDirectory('tickets');
  await write(
    path.join(repo, '.agents/tasks/TKT-0001-0025/TKT-0001/task.md'),
    ticketFrontmatter(),
  );
  await write(
    path.join(repo, '.agents/memory/architecture/example.md'),
    `---
id: example
title: Example
tags:
  - architecture
read_when:
  - testing
---

# Example
`,
  );

  run('tkt-sync.mjs', [repo]);
  run('tkt-sync.mjs', ['--check', repo]);
  run('tkt-validate.mjs', [path.join(repo, '.agents/tasks')]);

  const router = await readFile(
    path.join(repo, '.agents/tasks/index.yaml'),
    'utf8',
  );
  const shard = await readFile(
    path.join(repo, '.agents/tasks/TKT-0001-0025/index.yaml'),
    'utf8',
  );
  assert.match(router, /namespace: _shared/);
  assert.match(router, /TKT-0001-0025/);
  assert.match(shard, /id: TKT-0001/);
  assert.match(shard, /namespace: _shared/);
});

test('skill synchronization is idempotent', async () => {
  const repo = await temporaryDirectory('skills');
  await write(
    path.join(repo, '.agents/skills/example/SKILL.md'),
    `---
name: example
description: "Example skill."
disable-model-invocation: true
---

# Example
`,
  );

  run('sync-skills.mjs', ['--repo', repo]);
  run('sync-skills.mjs', ['--repo', repo, '--check']);

  const stub = await readFile(
    path.join(repo, '.claude/skills/example/SKILL.md'),
    'utf8',
  );
  const metadata = await readFile(
    path.join(repo, '.agents/skills/example/agents/openai.yaml'),
    'utf8',
  );
  assert.match(stub, /GENERATED BY nx run agent-tools:sync-skills/);
  assert.match(metadata, /allow_implicit_invocation: false/);
});

test('skill and chain ticket scaffolds write expected files', async () => {
  const repo = await temporaryDirectory('scaffolds');
  await mkdir(path.join(repo, '.agents/tasks'), { recursive: true });

  run('create-skill.mjs', [
    'sample-skill',
    'Sample description.',
    '--repo',
    repo,
    '--no-sync',
  ]);
  run('tkt-new-chain.mjs', [
    '--title',
    'Sample chain',
    '--repo-root',
    repo,
    '--namespace',
    'test-user',
    '--create-concept',
    '--create-plan',
    '--no-sync',
    '--step',
    'one:First step',
    '--step',
    'two:Second step',
  ]);

  assert.match(
    await readFile(
      path.join(repo, '.agents/skills/sample-skill/SKILL.md'),
      'utf8',
    ),
    /name: sample-skill/,
  );
  const chainTask = (id) =>
    readFile(
      path.join(repo, `.agents/tasks/test-user/TKT-0001-0025/${id}/task.md`),
      'utf8',
    );
  const task = await chainTask('TKT-0001');
  assert.match(task, /namespace: test-user/);
  assert.match(task, /Execution mode: `tkt-exec-chain`/);
  assert.match(task, /agent-tools:tkt-chain-check/);

  // A chain is an orchestrator, one ticket per step, and a final reviewer.
  assert.match(task, /chain_role: orchestrator/);
  assert.match(task, /chain_children:\n {2}- TKT-0002\n {2}- TKT-0003\n {2}- TKT-0004/);
  assert.match(task, /## Child Ticket Chain/);

  const firstWorker = await chainTask('TKT-0002');
  assert.match(firstWorker, /chain_role: worker/);
  assert.match(firstWorker, /chain_parent: TKT-0001/);
  assert.match(firstWorker, /Worker 1 of 2/);
  assert.match(firstWorker, /Branch: `tkt-0002-01-one`/);
  assert.doesNotMatch(firstWorker, /dependencies:/);

  const secondWorker = await chainTask('TKT-0003');
  assert.match(secondWorker, /Worker 2 of 2/);
  assert.match(secondWorker, /dependencies:\n {2}- TKT-0002/);

  const reviewer = await chainTask('TKT-0004');
  assert.match(reviewer, /chain_role: reviewer/);
  assert.match(reviewer, /chain_parent: TKT-0001/);
});

test('a chain scaffold refuses to collapse into a single ticket', async () => {
  const repo = await temporaryDirectory('chain-guard');
  await mkdir(path.join(repo, '.agents/tasks'), { recursive: true });

  const noSteps = run(
    'tkt-new-chain.mjs',
    ['--title', 'Lonely chain', '--repo-root', repo, '--no-sync'],
    { status: 2 },
  );
  assert.match(noSteps.stderr, /at least two --step values/);

  const oneStep = run(
    'tkt-new-chain.mjs',
    [
      '--title',
      'Lonely chain',
      '--repo-root',
      repo,
      '--no-sync',
      '--step',
      'only:Only step',
    ],
    { status: 2 },
  );
  assert.match(oneStep.stderr, /at least two --step values/);
});

test('validation fails while scaffold markers remain and on a childless chain', async () => {
  const repo = await temporaryDirectory('chain-validate');
  await mkdir(path.join(repo, '.agents/tasks'), { recursive: true });
  run('tkt-new-chain.mjs', [
    '--title',
    'Sample chain',
    '--repo-root',
    repo,
    '--namespace',
    'test-user',
    '--no-sync',
    '--step',
    'one:First step',
    '--step',
    'two:Second step',
  ]);

  const unfilled = run(
    'tkt-validate.mjs',
    [path.join(repo, '.agents/tasks')],
    { status: 1 },
  );
  assert.match(unfilled.stderr, /unfilled scaffold line/);

  await write(
    path.join(repo, '.agents/tasks/test-user/TKT-0001-0025/TKT-0005/task.md'),
    `---
id: TKT-0005
namespace: test-user
title: Childless chain
artifact: task
status: ready
owner: test-user
created: 2026-08-24
updated: 2026-08-24
chain_role: orchestrator
---

# Childless chain
`,
  );
  const childless = run(
    'tkt-validate.mjs',
    [path.join(repo, '.agents/tasks')],
    { status: 1 },
  );
  assert.match(childless.stderr, /chain orchestrator with no `chain_children`/);
});

test('migration dry-run and execution work without Python', async () => {
  const root = await temporaryDirectory('migration');
  const source = path.join(root, 'source');
  const target = path.join(root, 'target');
  await write(
    path.join(source, '.cursor/skills/example.md'),
    `---
name: example
description: Example imported skill.
---

# Example
`,
  );
  await mkdir(path.join(target, '.agents/tasks'), { recursive: true });

  run('migrate-cursor-setup.mjs', [
    '--source',
    source,
    '--repo',
    target,
    '--dry-run',
    '--no-sync',
  ]);
  run('migrate-cursor-setup.mjs', [
    '--source',
    source,
    '--repo',
    target,
    '--no-sync',
  ]);

  const migrated = await readFile(
    path.join(target, '.agents/skills/example/SKILL.md'),
    'utf8',
  );
  assert.match(migrated, /MIGRATED BY nx run agent-tools:migrate-cursor-setup/);
});

test('Codex trust uses an isolated configuration directory', async () => {
  const root = await temporaryDirectory('trust');
  const repo = path.join(root, 'repo');
  const codexHome = path.join(root, 'codex');
  await mkdir(repo, { recursive: true });

  run('trust-codex-project.mjs', [repo], { env: { CODEX_HOME: codexHome } });
  run('trust-codex-project.mjs', ['--check', repo], {
    env: { CODEX_HOME: codexHome },
  });

  const config = await readFile(path.join(codexHome, 'config.toml'), 'utf8');
  assert.match(config, /trust_level = "trusted"/);
});

test('all command entry points provide help', () => {
  const commands = [
    'create-skill.mjs',
    'migrate-cursor-setup.mjs',
    'sync-skills.mjs',
    'tkt-chain-check.mjs',
    'tkt-identity.mjs',
    'tkt-new.mjs',
    'tkt-new-chain.mjs',
    'tkt-sync.mjs',
    'tkt-validate.mjs',
    'trust-codex-project.mjs',
  ];
  for (const command of commands) {
    assert.match(run(command, ['--help']).stdout, /usage:/);
  }
});

test('developer namespaces allocate ticket ids independently', async () => {
  const repo = await temporaryDirectory('namespaces');
  await mkdir(path.join(repo, '.agents/tasks'), { recursive: true });
  await write(
    path.join(repo, '.agents/tasks/TKT-0001-0025/TKT-0001/task.md'),
    ticketFrontmatter('TKT-0001'),
  );

  const first = run('tkt-new.mjs', [
    '--title',
    'Alice ticket',
    '--repo-root',
    repo,
    '--namespace',
    'alice',
    '--no-sync',
  ]);
  const second = run('tkt-new.mjs', [
    '--title',
    'Bob ticket',
    '--repo-root',
    repo,
    '--namespace',
    'bob',
    '--no-sync',
  ]);
  const third = run('tkt-new.mjs', [
    '--title',
    'Alice follow-up',
    '--repo-root',
    repo,
    '--namespace',
    'alice',
    '--no-sync',
  ]);

  assert.match(first.stdout, /qualified: alice\/TKT-0001/);
  assert.match(second.stdout, /qualified: bob\/TKT-0001/);
  assert.match(third.stdout, /qualified: alice\/TKT-0002/);

  run('tkt-sync.mjs', [repo]);
  const validate = run('tkt-validate.mjs', [path.join(repo, '.agents/tasks')]);
  assert.match(validate.stdout, /tkt_validate ok/);

  const router = await readFile(
    path.join(repo, '.agents/tasks/index.yaml'),
    'utf8',
  );
  assert.match(router, /namespace: alice/);
  assert.match(router, /namespace: bob/);
  assert.match(router, /namespace: _shared/);

  const identity = await readFile(
    path.join(repo, '.agents/state/identity.local.yaml'),
    'utf8',
  );
  assert.match(identity, /github_login: alice/);
});

test('ticket allocation refuses to skip a missing id', async () => {
  const repo = await temporaryDirectory('ticket-gap');
  await mkdir(path.join(repo, '.agents/tasks'), { recursive: true });
  await write(
    path.join(repo, '.agents/tasks/gap-user/TKT-0001-0025/TKT-0001/task.md'),
    ticketFrontmatter('TKT-0001'),
  );
  await write(
    path.join(repo, '.agents/tasks/gap-user/TKT-0001-0025/TKT-0003/task.md'),
    ticketFrontmatter('TKT-0003'),
  );

  const result = run(
    'tkt-new.mjs',
    [
      '--title',
      'Should not skip',
      '--repo-root',
      repo,
      '--namespace',
      'gap-user',
      '--no-sync',
    ],
    { status: 1 },
  );
  assert.match(result.stderr, /missing ids.*TKT-0002/);
});

test('ticket creation rolls back when automatic index sync fails', async () => {
  const repo = await temporaryDirectory('ticket-sync-rollback');
  await mkdir(path.join(repo, '.agents/tasks'), { recursive: true });

  const result = run('tkt-new.mjs', [
    '--title',
    'Rollback when sync fails',
    '--repo-root',
    repo,
    '--namespace',
  'rollback-user',
  ], { status: 1 });

  assert.match(result.stderr, /ticket creation rolled back/);
  await assert.rejects(
    access(path.join(repo, '.agents/tasks/rollback-user/TKT-0001-0025/TKT-0001')),
  );
});
