import { lstat, mkdir, unlink } from 'node:fs/promises';
import path from 'node:path';
import { parseCli, runMain } from './lib/cli.mjs';
import {
  exists,
  isDirectory,
  listDirectories,
  listEntries,
  readText,
  relativePosix,
  removeDirectory,
  writeText,
} from './lib/fs-utils.mjs';

const GENERATED_MARKER =
  '<!-- GENERATED BY nx run agent-tools:sync-skills; DO NOT EDIT -->';
const LEGACY_MARKERS = [
  '<!-- GENERATED BY sync-skills.mjs; DO NOT EDIT -->',
  '<!-- GENERATED BY sync_skills.py; DO NOT EDIT -->',
  '<!-- GENERATED BY sync_claude_skills.py; DO NOT EDIT -->',
  '# Claude Compatibility Stub',
];
const INTERFACE_KEYS = ['display_name', 'short_description', 'default_prompt'];

function usage() {
  return `usage: sync-skills.mjs [-h] [--repo REPO] [--check] [--prune]

Sync generated skill adapters.

options:
  -h, --help   show this help message and exit
  --repo REPO  Repository root
  --check      Report drift and exit non-zero instead of writing
  --prune      Report user-owned Claude skill dirs without a canonical skill`;
}

async function main() {
  const args = parseCli(process.argv.slice(2), {
    repo: { type: 'string', default: '.' },
    check: { type: 'boolean' },
    prune: { type: 'boolean' },
  });
  if (args.help) {
    console.log(usage());
    return 0;
  }

  const repo = path.resolve(args.repo);
  const sourceRoot = path.join(repo, '.agents', 'skills');
  if (!(await isDirectory(sourceRoot))) {
    console.error(`error: missing canonical skills root: ${sourceRoot}`);
    return 1;
  }

  const skillDirs = [];
  for (const entry of await listDirectories(sourceRoot)) {
    const directory = path.join(sourceRoot, entry.name);
    if (await exists(path.join(directory, 'SKILL.md'))) {
      skillDirs.push(directory);
    }
  }

  const drift = [
    ...(await syncClaudeStubs(repo, skillDirs, args.check, args.prune)),
    ...(await syncCodexMetadata(repo, skillDirs, args.check)),
  ];
  if (args.check) {
    if (drift.length) {
      for (const item of drift) console.error(`drift: ${item}`);
      console.error(
        `sync_skills: ${drift.length} file(s) out of sync with SKILL.md`,
      );
      return 1;
    }
    console.log('sync_skills ok (no drift)');
    return 0;
  }
  console.log(`synced skill adapters (${drift.length} file(s) updated)`);
  return 0;
}

async function syncClaudeStubs(repo, skillDirs, check, prune) {
  const targetRoot = path.join(repo, '.claude', 'skills');
  const changed = [];
  if (await exists(targetRoot)) {
    const info = await lstat(targetRoot);
    if (info.isSymbolicLink()) {
      if (check) return [`${relativePosix(repo, targetRoot)} (symlink)`];
      await unlink(targetRoot);
    }
  }
  if (!check) {
    await mkdir(targetRoot, { recursive: true });
  } else if (!(await isDirectory(targetRoot))) {
    return skillDirs.map((directory) =>
      relativePosix(
        repo,
        path.join(targetRoot, path.basename(directory), 'SKILL.md'),
      ),
    );
  }

  const expected = new Set();
  for (const skillDir of skillDirs) {
    const name = path.basename(skillDir);
    expected.add(name);
    const target = path.join(targetRoot, name, 'SKILL.md');
    const desired = await renderStub(repo, path.join(skillDir, 'SKILL.md'));
    if ((await exists(target)) && !(await isGeneratedStub(target))) {
      if (!check) {
        console.error(
          `warning: preserving user-owned Claude skill stub: ${target}`,
        );
      }
      continue;
    }
    const current = await readText(target, '');
    if (current === desired) continue;
    changed.push(relativePosix(repo, target));
    if (!check) await writeText(target, desired);
  }

  if (await isDirectory(targetRoot)) {
    for (const entry of await listDirectories(targetRoot)) {
      const stale = path.join(targetRoot, entry.name);
      if (expected.has(entry.name)) continue;
      if (await isGeneratedSkillDir(stale)) {
        changed.push(`${relativePosix(repo, stale)} (stale)`);
        if (!check) await removeDirectory(stale);
      } else if (prune && !check) {
        console.error(
          `warning: --prune requested but preserving user-owned Claude skill dir: ${stale}`,
        );
      }
    }
  }
  return changed;
}

async function syncCodexMetadata(repo, skillDirs, check) {
  const changed = [];
  for (const skillDir of skillDirs) {
    const skillFile = path.join(skillDir, 'SKILL.md');
    const metadata = parseSkillFrontmatter(await readText(skillFile));
    const name = metadata.name || path.basename(skillDir);
    const allowImplicit = !asBool(metadata['disable-model-invocation']);
    const target = path.join(skillDir, 'agents', 'openai.yaml');
    const interfaceMetadata =
      (await readInterface(target)) ||
      defaultInterface(name, metadata.description || '');
    const desired = renderOpenaiYaml(interfaceMetadata, allowImplicit);
    const current = await readText(target, '');
    if (current === desired) continue;
    changed.push(relativePosix(repo, target));
    if (!check) await writeText(target, desired);
  }
  return changed;
}

async function renderStub(repo, skillFile) {
  const frontmatter = extractFrontmatter(await readText(skillFile));
  const body = [
    GENERATED_MARKER,
    '',
    '# Claude Compatibility Stub',
    '',
    'This file exists so Claude Code can discover this project skill.',
    '',
    'Canonical skill content lives at:',
    '',
    `- \`${relativePosix(repo, skillFile)}\``,
    '',
    'Read the canonical skill file before using this skill.',
    '',
    'Do not edit this stub manually. Regenerate it from the canonical `.agents/skills/` tree.',
    '',
  ].join('\n');
  return frontmatter ? `${frontmatter}\n\n${body}` : body;
}

function extractFrontmatter(content) {
  if (!content.startsWith('---\n')) return '';
  const end = content.indexOf('\n---', 4);
  return end === -1 ? '' : content.slice(0, end + 4);
}

function parseSkillFrontmatter(content) {
  const result = {};
  const block = extractFrontmatter(content);
  if (!block) return result;
  for (const line of block.slice(4, -4).split(/\r?\n/)) {
    const stripped = line.trim();
    if (!stripped || stripped.startsWith('#') || !stripped.includes(':'))
      continue;
    if (/^\s/.test(line)) continue;
    const separator = stripped.indexOf(':');
    result[stripped.slice(0, separator).trim()] = unquote(
      stripped.slice(separator + 1).trim(),
    );
  }
  return result;
}

async function readInterface(target) {
  if (!(await exists(target))) return null;
  const result = {};
  let inInterface = false;
  for (const line of (await readText(target)).split(/\r?\n/)) {
    if (line.startsWith('interface:')) {
      inInterface = true;
      continue;
    }
    if (!inInterface) continue;
    if (line && !/^\s/.test(line)) break;
    const stripped = line.trim();
    if (!stripped || !stripped.includes(':')) continue;
    const separator = stripped.indexOf(':');
    result[stripped.slice(0, separator).trim()] = unquote(
      stripped.slice(separator + 1).trim(),
    );
  }
  return Object.keys(result).length ? result : null;
}

function defaultInterface(name, description) {
  return {
    display_name: name.split('-').map(capitalize).join(' '),
    short_description: firstSentence(description),
    default_prompt: `Use $${name} in this repository.`,
  };
}

function firstSentence(description) {
  const normalized = description.split(/\s+/).filter(Boolean).join(' ');
  for (const stop of ['. ', '! ', '? ']) {
    const index = normalized.indexOf(stop);
    if (index !== -1 && index <= 120) return normalized.slice(0, index + 1);
  }
  if (normalized.length <= 120) return normalized;
  let clipped = normalized.slice(0, 117);
  if (clipped.includes(' '))
    clipped = clipped.slice(0, clipped.lastIndexOf(' '));
  return `${clipped.replace(/[ ,;:]+$/, '')}...`;
}

function renderOpenaiYaml(interfaceMetadata, allowImplicit) {
  const lines = ['interface:'];
  for (const key of INTERFACE_KEYS) {
    if (Object.hasOwn(interfaceMetadata, key)) {
      lines.push(`  ${key}: ${quoteYaml(interfaceMetadata[key])}`);
    }
  }
  lines.push('policy:');
  lines.push(
    `  allow_implicit_invocation: ${allowImplicit ? 'true' : 'false'}`,
  );
  return `${lines.join('\n')}\n`;
}

async function isGeneratedStub(target) {
  try {
    const content = await readText(target);
    return (
      content.includes(GENERATED_MARKER) ||
      LEGACY_MARKERS.some((marker) => content.includes(marker))
    );
  } catch {
    return false;
  }
}

async function isGeneratedSkillDir(directory) {
  const entries = await listEntries(directory);
  return (
    entries.length === 1 &&
    entries[0].name === 'SKILL.md' &&
    (await isGeneratedStub(path.join(directory, 'SKILL.md')))
  );
}

function asBool(value) {
  return (
    String(value ?? '')
      .trim()
      .toLowerCase() === 'true'
  );
}

function unquote(value) {
  if (
    value.length >= 2 &&
    value[0] === value.at(-1) &&
    (value[0] === '"' || value[0] === "'")
  ) {
    return value.slice(1, -1).replace(/\\"/g, '"').replace(/\\\\/g, '\\');
  }
  return value;
}

function quoteYaml(value) {
  return `"${String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function capitalize(value) {
  return value ? value[0].toUpperCase() + value.slice(1) : value;
}

await runMain(main);
