mod common;

use std::fs;

use common::{expected, fixture, read, run, write};

#[test]
fn sync_generates_stubs_and_codex_metadata() {
    let repo = fixture();
    let sync = run(&repo.root, &["skill", "sync"]);
    sync.assert_status(0);
    assert_eq!(sync.stdout, "synced skill adapters (4 file(s) updated)\n");
    assert_eq!(
        read(&repo.root, ".claude/skills/example/SKILL.md"),
        expected("claude-example-stub.md")
    );
    assert_eq!(
        read(&repo.root, ".claude/skills/custom/SKILL.md"),
        expected("claude-custom-stub.md")
    );
    assert_eq!(
        read(&repo.root, ".agents/skills/example/agents/openai.yaml"),
        expected("example-openai.yaml")
    );
    assert_eq!(
        read(&repo.root, ".agents/skills/custom/agents/openai.yaml"),
        expected("custom-openai.yaml")
    );

    let check = run(&repo.root, &["skill", "sync", "--check"]);
    check.assert_status(0);
    assert_eq!(check.stdout, "sync_skills ok (no drift)\n");
}

#[test]
fn check_reports_drift_before_writing() {
    let repo = fixture();
    let check = run(&repo.root, &["skill", "sync", "--check"]);
    check.assert_status(1);
    assert!(check
        .stderr
        .contains("drift: .claude/skills/example/SKILL.md"));
    assert!(check
        .stderr
        .contains("drift: .agents/skills/example/agents/openai.yaml"));
    assert!(check
        .stderr
        .contains("sync_skills: 4 file(s) out of sync with SKILL.md"));
    assert!(!repo.root.join(".claude").exists());
}

#[test]
fn user_owned_stubs_survive_and_stale_generated_dirs_are_removed() {
    let repo = fixture();
    write(
        &repo.root,
        ".claude/skills/example/SKILL.md",
        "# Mine\n\nHand written.\n",
    );
    write(
        &repo.root,
        ".claude/skills/legacy/SKILL.md",
        "---\nname: legacy\n---\n\n<!-- GENERATED BY nx run agent-tools:sync-skills; DO NOT EDIT -->\n\n# Claude Compatibility Stub\n",
    );
    write(
        &repo.root,
        ".claude/skills/personal/SKILL.md",
        "# Personal\n",
    );
    write(&repo.root, ".claude/skills/personal/notes.md", "keep\n");

    let sync = run(&repo.root, &["skill", "sync", "--prune"]);
    sync.assert_status(0);
    assert!(sync
        .stderr
        .contains("preserving user-owned Claude skill stub"));
    assert!(sync
        .stderr
        .contains("preserving user-owned Claude skill dir"));
    assert_eq!(
        read(&repo.root, ".claude/skills/example/SKILL.md"),
        "# Mine\n\nHand written.\n"
    );
    assert!(!repo.root.join(".claude/skills/legacy").exists());
    assert!(repo.root.join(".claude/skills/personal/notes.md").exists());
}

#[test]
fn legacy_markers_are_replaced() {
    let repo = fixture();
    write(
        &repo.root,
        ".claude/skills/example/SKILL.md",
        "---\nname: example\n---\n\n<!-- GENERATED BY nx run agent-tools:sync-skills; DO NOT EDIT -->\n\n# Claude Compatibility Stub\n",
    );
    run(&repo.root, &["skill", "sync"]).assert_status(0);
    assert_eq!(
        read(&repo.root, ".claude/skills/example/SKILL.md"),
        expected("claude-example-stub.md")
    );
}

#[test]
fn missing_skills_root_fails() {
    let repo = fixture();
    fs::remove_dir_all(repo.root.join(".agents/skills")).unwrap();
    let sync = run(&repo.root, &["skill", "sync"]);
    sync.assert_status(1);
    assert!(sync.stderr.contains("missing canonical skills root"));
}

#[cfg(unix)]
#[test]
fn sync_ignores_symlinked_skill_directories() {
    let repo = fixture();
    let outside = tempfile::tempdir().unwrap();
    fs::write(
        outside.path().join("SKILL.md"),
        "---\nname: linked\ndescription: Must stay outside.\n---\n",
    )
    .unwrap();
    std::os::unix::fs::symlink(outside.path(), repo.root.join(".agents/skills/linked")).unwrap();

    run(&repo.root, &["skill", "sync"]).assert_status(0);
    assert!(!outside.path().join("agents/openai.yaml").exists());
    assert!(!repo.root.join(".claude/skills/linked").exists());
}
